#!/bin/bash
# Deploy VKD Website - Multiple Options

echo "=== VKD Website Deployment Options ==="
echo ""
echo "1. NETLIFY (Recommended - Free)"
echo "   - Go to: https://netlify.com"
echo "   - Create account"
echo "   - Drag & drop 'dist' folder to deploy"
echo ""
echo "2. VERCEL (Free)"
echo "   - Go to: https://vercel.com"
echo "   - Import from GitHub or upload"
echo ""
echo "3. GITHUB PAGES (Free)"
echo "   - Create repo on GitHub"
echo "   - Push dist folder contents"
echo "   - Enable Pages in Settings"
echo ""
echo "4. SURGE.SH (Free CLI)"
echo "   - npm install -g surge"
echo "   - cd dist && surge"
echo ""
echo "5. IPFS (Decentralized)"
echo "   - Use pinata.cloud or ipfs.io"
echo ""
echo "=== Quick Test Local ==="
echo "npx serve dist"
echo "# or"
echo "python -m http.server 8080 -d dist"
