-- VKD Products Database Import Script
-- Source: samngoclinhvkdgroup.com (43 products, scraped 2026-07-17)
-- Target: PostgreSQL / Supabase

-- Create tables
CREATE TABLE IF NOT EXISTS vkd_categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  description TEXT
  );

CREATE TABLE IF NOT EXISTS vkd_products (
  id SERIAL PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  name_ascii TEXT,
  price_vnd INTEGER,
  price_usd NUMERIC(10,2),
  currency TEXT DEFAULT 'VND',
  category_id TEXT REFERENCES vkd_categories(id),
  active_ingredient TEXT,
  badge TEXT,
  image_url TEXT,
  image_local TEXT,
  detail_url TEXT,
  source TEXT,
  scraped_at DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert categories
INSERT INTO vkd_categories (id, label, description) VALUES ('ginseng', 'Sâm Củ Tươi & Sâm Khô', 'Sâm Ngọc Linh chính gốc Tu Mơ Rông') ON CONFLICT (id) DO NOTHING;
INSERT INTO vkd_categories (id, label, description) VALUES ('supplements', 'Thực Phẩm Bảo Vệ Sức Khỏe', 'Dịch chiết sâm, viên nang, nước uống sâm') ON CONFLICT (id) DO NOTHING;
INSERT INTO vkd_categories (id, label, description) VALUES ('tea_wine', 'Trà & Đồ Uống Sâm', 'Trà sâm túi lọc, rượu sâm Ngọc Linh cao cấp') ON CONFLICT (id) DO NOTHING;
INSERT INTO vkd_categories (id, label, description) VALUES ('cosmetics', 'Mỹ Phẩm & Làm Đẹp', 'Collagen sâm, kem dưỡng sâm') ON CONFLICT (id) DO NOTHING;

-- Insert products
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-001', 'sam-ngoc-linh-thai-lat-ngam-mat-ong', 'Sâm Ngọc Linh thái lát ngâm mật ong', 'Sam Ngoc Linh thai lat ngam mat ong', 2500000, 98.04, 'VND', 'ginseng', 'Majonoside R2 (MR2) — độc quyền Ngọc Linh', 'Quốc Bảo', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/SNL-Thai-Lat.png', 'images/01-sam-ngoc-linh-thai-lat-ngam-mat-ong.png', 'https://samngoclinhvkdgroup.com/san-pham/sam-ngoc-linh-thai-lat-ngam-mat-ong/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-002', 'cao-sam-ngoc-linh-mat-ong', 'Cao Sâm Ngọc Linh Mật Ong', 'Cao Sam Ngoc Linh Mat Ong', 2200000, 86.27, 'VND', 'supplements', 'Cao đặc 70% + Saponin MR2', 'Hàm lượng cao', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-9.png', 'images/02-cao-sam-ngoc-linh-mat-ong.png', 'https://samngoclinhvkdgroup.com/san-pham/cao-sam-ngoc-linh-mat-ong/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-003', 'nuoc-cot-sam-ngoc-linh', 'Nước Cốt Sâm Ngọc Linh', 'Nuoc Cot Sam Ngoc Linh', 445000, 17.45, 'VND', 'supplements', 'Chiết xuất sâm 8–10 năm tuổi', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-8.png', 'images/03-nuoc-cot-sam-ngoc-linh.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-cot-sam-ngoc-linh/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-004', 'giai-doc-gan-panaxx-naturis', 'Giải Độc Gan Panaxx Naturis', 'Giai Đoc Gan Panaxx Naturis', 440000, 17.25, 'VND', 'supplements', 'MR2 + Cà gai leo + Khúng khéng', 'Bảo vệ gan', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-7.png', 'images/04-giai-doc-gan-panaxx-naturis.png', 'https://samngoclinhvkdgroup.com/san-pham/giai-doc-gan-panaxx-naturis/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-005', 'nuoc-sam-ngoc-linh-panaxx', 'NƯỚC SÂM NGỌC LINH PANAXX', 'NUOC SAM NGOC LINH PANAXX', NULL, NULL, 'VND', 'supplements', 'Chiết xuất sâm Ngọc Linh 0,05%', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/sp1.png', 'images/05-nuoc-sam-ngoc-linh-panaxx.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-sam-ngoc-linh-panaxx/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-006', 'nuoc-sam-ngoc-linh-panaxx-vi-chanh-leo', 'NƯỚC SÂM NGỌC LINH PANAXX – VỊ CHANH LEO', 'NUOC SAM NGOC LINH PANAXX – VI CHANH LEO', NULL, NULL, 'VND', 'supplements', 'Chiết xuất sâm Ngọc Linh + Caffeine', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/sp2.png', 'images/06-nuoc-sam-ngoc-linh-panaxx-vi-chanh-leo.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-sam-ngoc-linh-panaxx-vi-chanh-leo/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-007', 'nuoc-sam-ngoc-linh-panaxx-vi-oi-hong', 'NƯỚC SÂM NGỌC LINH PANAXX – VỊ ỔI HỒNG', 'NUOC SAM NGOC LINH PANAXX – VI OI HONG', NULL, NULL, 'VND', 'supplements', 'Chiết xuất sâm Ngọc Linh + Caffeine', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/sp3.png', 'images/07-nuoc-sam-ngoc-linh-panaxx-vi-oi-hong.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-sam-ngoc-linh-panaxx-vi-oi-hong/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-008', 'keo-sam-ngoc-linh-panaxx-candy', 'Kẹo Sâm Ngọc Linh (PanaxX Candy)', 'Keo Sam Ngoc Linh (PanaxX Candy)', 72000, 2.82, 'VND', 'supplements', 'Saponin sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/keo.png', 'images/08-keo-sam-ngoc-linh-panaxx-candy.png', 'https://samngoclinhvkdgroup.com/san-pham/keo-sam-ngoc-linh-panaxx-candy/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-009', 'banh-sam-ngoc-linh-panaxx-cookie', 'Bánh Sâm Ngọc Linh (PanaxX Cookie)', 'Banh Sam Ngoc Linh (PanaxX Cookie)', 58000, 2.27, 'VND', 'supplements', 'Chiết xuất sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/banh.png', 'images/09-banh-sam-ngoc-linh-panaxx-cookie.png', 'https://samngoclinhvkdgroup.com/san-pham/banh-sam-ngoc-linh-panaxx-cookie/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-010', 'panaxx-super-drink-190ml-ban-moi', 'Panaxx Super Drink 190ml (Bản Mới)', 'Panaxx Super Drink 190ml (Ban Moi)', 15000, 0.59, 'VND', 'supplements', 'MR2 + Vitamin B3/B6', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-6.png', 'images/10-panaxx-super-drink-190ml-ban-moi.png', 'https://samngoclinhvkdgroup.com/san-pham/panaxx-super-drink-190ml-ban-moi/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-011', 'tra-sam-ngoc-linh', 'Trà Sâm Ngọc Linh', 'Tra Sam Ngoc Linh', 345000, 13.53, 'VND', 'tea_wine', 'Lát sâm Ngọc Linh sấy khô', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/tra.png', 'images/11-tra-sam-ngoc-linh.png', 'https://samngoclinhvkdgroup.com/san-pham/tra-sam-ngoc-linh/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-012', 'set-5-lon-nuoc-tang-luc-5-vi', 'Set 5 Lon Nước Tăng Lực (5 Vị)', 'Set 5 Lon Nuoc Tang Luc (5 Vi)', 130000, 5.1, 'VND', 'tea_wine', 'Saponin MR2 + Taurine + Vitamin B', 'Ngũ Hành', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-5.png', 'images/12-set-5-lon-nuoc-tang-luc-5-vi.png', 'https://samngoclinhvkdgroup.com/san-pham/set-5-lon-nuoc-tang-luc-5-vi/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-013', 'panaxx-ban-kim-325ml', 'PanaxX – Bản Kim 325ml', 'PanaxX – Ban Kim 325ml', 26000, 1.02, 'VND', 'tea_wine', 'Sâm Ngọc Linh 0,05% — Hương Xoài', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/kim.png', 'images/13-panaxx-ban-kim-325ml.png', 'https://samngoclinhvkdgroup.com/san-pham/panaxx-ban-kim-325ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-014', 'panaxx-ban-moc-325ml', 'PanaxX – Bản Mộc 325ml', 'PanaxX – Ban Moc 325ml', 26000, 1.02, 'VND', 'tea_wine', 'Sâm Ngọc Linh 0,05% — Hương Dưa Gang', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/moc.png', 'images/14-panaxx-ban-moc-325ml.png', 'https://samngoclinhvkdgroup.com/san-pham/panaxx-ban-moc-325ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-015', 'panaxx-ban-thuy-325ml', 'PanaxX – Bản Thuỷ 325ml', 'PanaxX – Ban Thuy 325ml', 26000, 1.02, 'VND', 'tea_wine', 'Sâm Ngọc Linh 0,05% — Hương Chanh Dây', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/thuy.png', 'images/15-panaxx-ban-thuy-325ml.png', 'https://samngoclinhvkdgroup.com/san-pham/panaxx-ban-thuy-325ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-016', 'panaxx-ban-hoa-325ml', 'PanaxX – Bản Hoả 325ml', 'PanaxX – Ban Hoa 325ml', 26000, 1.02, 'VND', 'tea_wine', 'Sâm Ngọc Linh 0,05% — Hương Ổi Hồng', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/hoa.png', 'images/16-panaxx-ban-hoa-325ml.png', 'https://samngoclinhvkdgroup.com/san-pham/panaxx-ban-hoa-325ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-017', 'ruou-ngoc-de-thien-huong-750ml', 'Rượu Ngọc Đế -Thiên Hương 750ml', 'Ruou Ngoc Đe -Thien Huong 750ml', 1750000, 68.63, 'VND', 'tea_wine', 'Sâm Ngọc Linh ngâm ủ truyền thống', 'Cao cấp', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/Ruoungocde2.png', 'images/17-ruou-ngoc-de-thien-huong-750ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-thien-huong-750ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-018', 'ruou-ngoc-de-sam-ngoc-linh-12-nam-500ml', 'Rượu Ngọc Đế Sâm Ngọc Linh 12 năm – 500ml', 'Ruou Ngoc Đe Sam Ngoc Linh 12 nam – 500ml', 1118000, 43.84, 'VND', 'tea_wine', 'Sâm 12 năm tuổi + Hồng Sâm + Tam Thất', '12 năm', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/ruou-sam-12-nam.png', 'images/18-ruou-ngoc-de-sam-ngoc-linh-12-nam-500ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-sam-ngoc-linh-12-nam-500ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-019', 'ruou-ngoc-de-sam-ngoc-linh-10-nam-500ml', 'Rượu Ngọc Đế Sâm Ngọc Linh 10 năm – 500ml', 'Ruou Ngoc Đe Sam Ngoc Linh 10 nam – 500ml', 980000, 38.43, 'VND', 'tea_wine', 'Sâm 10 năm tuổi — chưng cất châu Âu', '10 năm', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/ruou-sam-10-nam.png', 'images/19-ruou-ngoc-de-sam-ngoc-linh-10-nam-500ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-sam-ngoc-linh-10-nam-500ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-020', 'ruou-ngoc-de-thang-long-chai-cao-500ml', 'Rượu Ngọc Đế – Thăng Long (Chai cao) 500ml', 'Ruou Ngoc Đe – Thang Long (Chai cao) 500ml', 860000, 33.73, 'VND', 'tea_wine', 'Sâm Ngọc Linh 8+ năm tuổi', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/Ruoungocde3.png', 'images/20-ruou-ngoc-de-thang-long-chai-cao-500ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-thang-long-chai-cao-500ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-021', 'ruou-ngoc-de-thang-long-chai-thap-500ml', 'Rượu Ngọc Đế – Thăng Long (Chai thấp) 500ml', 'Ruou Ngoc Đe – Thang Long (Chai thap) 500ml', 860000, 33.73, 'VND', 'tea_wine', 'Sâm Ngọc Linh 8+ năm tuổi', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/Ruoungocde1.png', 'images/21-ruou-ngoc-de-thang-long-chai-thap-500ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-thang-long-chai-thap-500ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-022', 'ruou-ngoc-de-sam-ngoc-linh-normal-500ml', 'Rượu Ngọc Đế Sâm Ngọc Linh Normal 500ml', 'Ruou Ngoc Đe Sam Ngoc Linh Normal 500ml', 585000, 22.94, 'VND', 'tea_wine', 'Sâm Ngọc Linh 8+ năm + Tam Thất + Câu Kỉ', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/ruou-sam-normal.png', 'images/22-ruou-ngoc-de-sam-ngoc-linh-normal-500ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-sam-ngoc-linh-normal-500ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-023', 'ruou-sam-ngoc-linh-xe-dang', 'Rượu Sâm Ngọc Linh Xê Đăng', 'Ruou Sam Ngoc Linh Xe Đang', 690000, 27.06, 'VND', 'tea_wine', 'Sâm Ngọc Linh + Dược liệu quý', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-4.png', 'images/23-ruou-sam-ngoc-linh-xe-dang.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-sam-ngoc-linh-xe-dang/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-024', 'ruou-sam-ngoc-linh-19-5-do', 'Rượu Sâm Ngọc Linh 19.5 Độ', 'Ruou Sam Ngoc Linh 19.5 Đo', 370000, 14.51, 'VND', 'tea_wine', 'Sâm Ngọc Linh 8+ năm — 19.5°', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-2.png', 'images/24-ruou-sam-ngoc-linh-19-5-do.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-sam-ngoc-linh-19-5-do/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-025', 'combo-2-chai-ruou-sam-ngoc-linh-19-5-do', 'Combo 2 Chai Rượu Sâm Ngọc Linh 19.5 Độ', 'Combo 2 Chai Ruou Sam Ngoc Linh 19.5 Đo', 715000, 28.04, 'VND', 'tea_wine', 'Combo 2 chai — tiết kiệm', 'Combo', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-3.png', 'images/25-combo-2-chai-ruou-sam-ngoc-linh-19-5-do.png', 'https://samngoclinhvkdgroup.com/san-pham/combo-2-chai-ruou-sam-ngoc-linh-19-5-do/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-026', 'ruou-ngoc-de-pho-thong-300ml', 'Rượu Ngọc Đế Phổ Thông 300ml', 'Ruou Ngoc Đe Pho Thong 300ml', 200000, 7.84, 'VND', 'tea_wine', 'Sâm Ngọc Linh ngâm ủ', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-1.png', 'images/26-ruou-ngoc-de-pho-thong-300ml.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-ngoc-de-pho-thong-300ml/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-027', 'ruou-kim-boi', 'Rượu Kim Bôi', 'Ruou Kim Boi', 72000, 2.82, 'VND', 'tea_wine', 'Rượu gạo truyền thống + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/Ruoungocde.png', 'images/27-ruou-kim-boi.png', 'https://samngoclinhvkdgroup.com/san-pham/ruou-kim-boi/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-028', 'men-kim-boi', 'Men Kim Bôi', 'Men Kim Boi', 80000, 3.14, 'VND', 'tea_wine', '36 vị thuốc bắc — men rượu truyền thống', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-1-1.png', 'images/28-men-kim-boi.png', 'https://samngoclinhvkdgroup.com/san-pham/men-kim-boi/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-029', 'bo-tre-hoa-combo-big-size', 'Bộ Trẻ Hóa Combo (Big Size)', 'Bo Tre Hoa Combo (Big Size)', 8760000, 343.53, 'VND', 'cosmetics', 'Sâm Ngọc Linh + PCG (Tam Thất + Đông Trùng + Linh Chi)', 'Combo Premium', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-15.png', 'images/29-bo-tre-hoa-combo-big-size.png', 'https://samngoclinhvkdgroup.com/san-pham/bo-tre-hoa-combo-big-size/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-030', 'bo-phuc-hoi-da', 'Bộ phục hồi da', 'Bo phuc hoi da', 3230000, 126.67, 'VND', 'cosmetics', 'Chiết xuất sâm Ngọc Linh PN’s Choice', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham.png', 'images/30-bo-phuc-hoi-da.png', 'https://samngoclinhvkdgroup.com/san-pham/bo-phuc-hoi-da/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-031', 'nuoc-tre-hoa-da-purely-refreshing', 'Nước Trẻ Hóa Da (Purely Refreshing)', 'Nuoc Tre Hoa Da (Purely Refreshing)', 3470000, 136.08, 'VND', 'cosmetics', 'Gold Water + Saponin cô đặc', 'Nước thần', 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-13.png', 'images/31-nuoc-tre-hoa-da-purely-refreshing.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-tre-hoa-da-purely-refreshing/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-032', 'bo-tre-hoa-da-combo-mini-size', 'Bộ Trẻ Hóa Da Combo (Mini Size)', 'Bo Tre Hoa Da Combo (Mini Size)', 1850000, 72.55, 'VND', 'cosmetics', 'Combo 4 sản phẩm PN’s Choice', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-14.png', 'images/32-bo-tre-hoa-da-combo-mini-size.png', 'https://samngoclinhvkdgroup.com/san-pham/bo-tre-hoa-da-combo-mini-size/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-033', 'kem-duong-ban-dem-night-cream', 'Kem Dưỡng Ban Đêm (Night Cream)', 'Kem Duong Ban Đem (Night Cream)', 1900000, 74.51, 'VND', 'cosmetics', 'Advanced Night Repair + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-11.png', 'images/33-kem-duong-ban-dem-night-cream.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-duong-ban-dem-night-cream/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-034', 'serum-duong-da-serum', 'Serum Dưỡng Da (Serum)', 'Serum Duong Da (Serum)', 1780000, 69.8, 'VND', 'cosmetics', 'Power Rejuvenation Serum + Saponin', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-12.png', 'images/34-serum-duong-da-serum.png', 'https://samngoclinhvkdgroup.com/san-pham/serum-duong-da-serum/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-035', 'kem-duong-ban-ngay-day-cream', 'Kem Dưỡng Ban Ngày (Day Cream)', 'Kem Duong Ban Ngay (Day Cream)', 1580000, 61.96, 'VND', 'cosmetics', 'Advanced Day Repair + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-11.png', 'images/35-kem-duong-ban-ngay-day-cream.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-duong-ban-ngay-day-cream/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-036', 'kem-mat-eyes-cream', 'Kem Mắt (Eyes Cream)', 'Kem Mat (Eyes Cream)', 1150000, 45.1, 'VND', 'cosmetics', 'Active Intensive Eye Cream + Sâm', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-17.png', 'images/36-kem-mat-eyes-cream.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-mat-eyes-cream/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-037', 'kem-duong-ban-dem-night-cream-pn-s', 'Kem Dưỡng Ban Đêm (Night Cream) — Pn’s', 'Kem Duong Ban Đem (Night Cream) — Pn’s', 780000, 30.59, 'VND', 'cosmetics', 'Micellar Repair Night — Saponin cô đặc', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-22.png', 'images/37-kem-duong-ban-dem-night-cream-pn-s.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-ban-dem-night-cream/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-038', 'kem-chong-nang-daily-uv', 'Kem Chống Nắng (Daily UV)', 'Kem Chong Nang (Daily UV)', 850000, 33.33, 'VND', 'cosmetics', 'SPF 50 PA++++ + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-10.png', 'images/38-kem-chong-nang-daily-uv.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-chong-nang-daily-uv/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-039', 'nuoc-duong-da-micellar-serum', 'Nước Dưỡng Da (Micellar Serum)', 'Nuoc Duong Da (Micellar Serum)', 850000, 33.33, 'VND', 'cosmetics', 'Micellar Repair Serum — Saponin', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-18.png', 'images/39-nuoc-duong-da-micellar-serum.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-duong-da-micellar-serum/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-040', 'kem-ban-ngay-day-cream-pn-s', 'Kem Ban Ngày (Day Cream) — Pn’s', 'Kem Ban Ngay (Day Cream) — Pn’s', 580000, 22.75, 'VND', 'cosmetics', 'Micellar Repair Day + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-21.png', 'images/40-kem-ban-ngay-day-cream-pn-s.png', 'https://samngoclinhvkdgroup.com/san-pham/kem-ban-ngay-day-cream/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-041', 'nuoc-can-bang-micellar-toner', 'Nước Cân Bằng (Micellar Toner)', 'Nuoc Can Bang (Micellar Toner)', 560000, 21.96, 'VND', 'cosmetics', 'Micellar Repair Toner — Saponin', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-19.png', 'images/41-nuoc-can-bang-micellar-toner.png', 'https://samngoclinhvkdgroup.com/san-pham/nuoc-can-bang-micellar-toner/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-042', 'sua-rua-mat-micellar-cleaner', 'Sữa Rửa Mặt (Micellar Cleaner)', 'Sua Rua Mat (Micellar Cleaner)', 450000, 17.65, 'VND', 'cosmetics', 'Micellar Repair Cleaner + Sâm', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-20.png', 'images/42-sua-rua-mat-micellar-cleaner.png', 'https://samngoclinhvkdgroup.com/san-pham/sua-rua-mat-micellar-cleaner/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;
INSERT INTO vkd_products (sku, slug, name, name_ascii, price_vnd, price_usd, currency, category_id, active_ingredient, badge, image_url, image_local, detail_url, source, scraped_at) VALUES ('VKD-043', 'mat-na-duong-da-face-mask-5-mieng', 'Mặt Nạ Dưỡng Da (Face Mask) 5 Miếng', 'Mat Na Duong Da (Face Mask) 5 Mieng', 250000, 9.8, 'VND', 'cosmetics', 'Rejuvenating Face Mask + Sâm Ngọc Linh', NULL, 'https://samngoclinhvkdgroup.com/wp-content/uploads/2026/06/my-pham-16.png', 'images/43-mat-na-duong-da-face-mask-5-mieng.png', 'https://samngoclinhvkdgroup.com/san-pham/mat-na-duong-da-face-mask-5-mieng/', 'samngoclinhvkdgroup.com', '2026-07-17') ON CONFLICT (sku) DO UPDATE SET name=EXCLUDED.name, price_vnd=EXCLUDED.price_vnd, image_url=EXCLUDED.image_url, detail_url=EXCLUDED.detail_url;

-- Verify
SELECT category_id, COUNT(*) FROM vkd_products GROUP BY category_id ORDER BY category_id;
SELECT COUNT(*) AS total_products FROM vkd_products;